"""SQLite mention detection tables

Revision ID: 0002
Revises: 0001
Create Date: 2024-06-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建引用检测记录表
    op.create_table('mention_checks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('brands_checked', sa.Text(), nullable=False),
        sa.Column('models_used', sa.Text(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('total_mentions', sa.Integer(), nullable=True),
        sa.Column('mention_rate', sa.Float(), nullable=True),
        sa.Column('avg_confidence', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('extra_metadata', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_checks_project_id'), 'mention_checks', ['project_id'], unique=False)
    op.create_index(op.f('ix_mention_checks_user_id'), 'mention_checks', ['user_id'], unique=False)
    op.create_index(op.f('ix_mention_checks_created_at'), 'mention_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_mention_checks_status'), 'mention_checks', ['status'], unique=False)
    
    # 创建模型检测结果表
    op.create_table('mention_results',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('check_id', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('response_text', sa.Text(), nullable=False),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['check_id'], ['mention_checks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_results_check_id'), 'mention_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_mention_results_model'), 'mention_results', ['model'], unique=False)
    
    # 创建品牌提及详情表
    op.create_table('brand_mentions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('result_id', sa.String(), nullable=False),
        sa.Column('brand', sa.String(), nullable=False),
        sa.Column('mentioned', sa.Boolean(), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('context_snippet', sa.Text(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['result_id'], ['mention_results.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_mentions_result_id'), 'brand_mentions', ['result_id'], unique=False)
    op.create_index(op.f('ix_brand_mentions_brand'), 'brand_mentions', ['brand'], unique=False)
    op.create_index(op.f('ix_brand_mentions_mentioned'), 'brand_mentions', ['mentioned'], unique=False)
    
    # 创建Prompt模板表
    op.create_table('prompt_templates',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('template', sa.Text(), nullable=False),
        sa.Column('variables', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_user_id'), 'prompt_templates', ['user_id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_templates_is_public'), 'prompt_templates', ['is_public'], unique=False)
    
    # 创建统计分析缓存表
    op.create_table('analytics_cache',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('cache_key', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(), nullable=True),
        sa.Column('brand', sa.String(), nullable=True),
        sa.Column('timeframe', sa.String(), nullable=True),
        sa.Column('data', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cache_key')
    )
    op.create_index(op.f('ix_analytics_cache_cache_key'), 'analytics_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_analytics_cache_expires_at'), 'analytics_cache', ['expires_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除统计分析缓存表
    op.drop_index(op.f('ix_analytics_cache_expires_at'), table_name='analytics_cache')
    op.drop_index(op.f('ix_analytics_cache_cache_key'), table_name='analytics_cache')
    op.drop_table('analytics_cache')
    
    # 删除Prompt模板表
    op.drop_index(op.f('ix_prompt_templates_is_public'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_user_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    
    # 删除品牌提及详情表
    op.drop_index(op.f('ix_brand_mentions_mentioned'), table_name='brand_mentions')
    op.drop_index(op.f('ix_brand_mentions_brand'), table_name='brand_mentions')
    op.drop_index(op.f('ix_brand_mentions_result_id'), table_name='brand_mentions')
    op.drop_table('brand_mentions')
    
    # 删除模型检测结果表
    op.drop_index(op.f('ix_mention_results_model'), table_name='mention_results')
    op.drop_index(op.f('ix_mention_results_check_id'), table_name='mention_results')
    op.drop_table('mention_results')
    
    # 删除引用检测记录表
    op.drop_index(op.f('ix_mention_checks_status'), table_name='mention_checks')
    op.drop_index(op.f('ix_mention_checks_created_at'), table_name='mention_checks')
    op.drop_index(op.f('ix_mention_checks_user_id'), table_name='mention_checks')
    op.drop_index(op.f('ix_mention_checks_project_id'), table_name='mention_checks')
    op.drop_table('mention_checks')
    
    # ### end Alembic commands ###
